%prod.kafka.bootstrap.servers=kafka:9092 
%dev.kafka.bootstrap.servers=sensorkafka-kafka-tls-bootstrap-sensortracking.apps.ussredhat.dbarh.demo:443
%dev.quarkus.http.port=8081
mp.messaging.outgoing.sensor-data.topic=sensor-data
mp.messaging.outgoing.sensor-data.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
kafka.security.protocol = SSL
kafka.ssl.truststore.location = /home/david/Work/Demos/sensorTracking/mykeystore.jks
kafka.ssl.truststore.password = sensorcapass