%prod.kafka.bootstrap.servers=kafka:9092 
%dev.kafka.bootstrap.servers=sensorkafka-brokerpool-tls-0-sensortracking.apps.ussredhat.dbarh.demo:443
%dev.quarkus.http.port=8081
mp.messaging.outgoing.sensor-data.topic=sensor-data