sensor.id=${SENSOR_ID:sensor-1}
sensor.start.lat=${SENSOR_START_LAT:38.8977}
sensor.start.lng=${SENSOR_START_LNG:-77.0365}

%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
%dev.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:sensorkafka-kafka-tls-bootstrap-sensortracking.apps.ussredhat.dbarh.demo:443}
%dev.quarkus.http.port=8081
mp.messaging.outgoing.sensor-data.topic=sensor-data
mp.messaging.outgoing.sensor-data.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
kafka.security.protocol = SSL
kafka.ssl.truststore.location = ${KAFKA_SSL_TRUSTSTORE_LOCATION:/home/david/Work/Demos/sensorTracking/mykeystore.jks}
kafka.ssl.truststore.password = ${KAFKA_SSL_TRUSTSTORE_PASSWORD:sensorcapass}